# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ads_message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import prop_struct_pb2 as prop__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x64s_message.proto\x12\rdobala.garden\x1a\x11prop_struct.proto\"m\n\x05PBAds\x12\x0e\n\x06\x61\x64s_id\x18\x01 \x01(\x05\x12\x12\n\nstart_time\x18\x03 \x01(\x03\x12\x13\n\x0bis_received\x18\x04 \x01(\x05\x12\x15\n\rreceived_time\x18\x05 \x01(\x03\x12\x14\n\x0cis_skip_prop\x18\x06 \x01(\x08\"0\n\nPBWxUnitId\x12\x0e\n\x06\x61\x64s_id\x18\x01 \x01(\x05\x12\x12\n\nwx_unit_id\x18\x02 \x01(\t\"n\n\x19SCNotifyUpdateAdsFullInfo\x12!\n\x03\x61\x64s\x18\x01 \x03(\x0b\x32\x14.dobala.garden.PBAds\x12.\n\x0bwx_unit_ids\x18\x02 \x03(\x0b\x32\x19.dobala.garden.PBWxUnitId\"6\n\x11SCNotifyUpdateAds\x12!\n\x03\x61\x64s\x18\x01 \x03(\x0b\x32\x14.dobala.garden.PBAds\"E\n\x13SCNotifyAdsWxUnitId\x12.\n\x0bwx_unit_ids\x18\x01 \x03(\x0b\x32\x19.dobala.garden.PBWxUnitId\"2\n\nCSAdsClick\x12\x0e\n\x06\x61\x64s_id\x18\x01 \x01(\x05\x12\x14\n\x0cis_skip_prop\x18\x02 \x01(\x08\"2\n\nSCAdsClick\x12\x0e\n\x06\x61\x64s_id\x18\x01 \x01(\x05\x12\x14\n\x0cis_skip_prop\x18\x02 \x01(\x08\x42\x13\xaa\x02\x10SteamClient.Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ads_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020SteamClient.Game'
  _globals['_PBADS']._serialized_start=55
  _globals['_PBADS']._serialized_end=164
  _globals['_PBWXUNITID']._serialized_start=166
  _globals['_PBWXUNITID']._serialized_end=214
  _globals['_SCNOTIFYUPDATEADSFULLINFO']._serialized_start=216
  _globals['_SCNOTIFYUPDATEADSFULLINFO']._serialized_end=326
  _globals['_SCNOTIFYUPDATEADS']._serialized_start=328
  _globals['_SCNOTIFYUPDATEADS']._serialized_end=382
  _globals['_SCNOTIFYADSWXUNITID']._serialized_start=384
  _globals['_SCNOTIFYADSWXUNITID']._serialized_end=453
  _globals['_CSADSCLICK']._serialized_start=455
  _globals['_CSADSCLICK']._serialized_end=505
  _globals['_SCADSCLICK']._serialized_start=507
  _globals['_SCADSCLICK']._serialized_end=557
# @@protoc_insertion_point(module_scope)
