# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gift_message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import prop_struct_pb2 as prop__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12gift_message.proto\x12\rdobala.garden\x1a\x11prop_struct.proto\"\x0c\n\nPBGiftData\"S\n\x06PBGift\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12)\n\x06status\x18\x03 \x01(\x0e\x32\x19.dobala.garden.GiftStatus\"e\n\x14SCNotifyGiftFullInfo\x12\'\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x19.dobala.garden.PBGiftData\x12$\n\x05gifts\x18\x02 \x03(\x0b\x32\x15.dobala.garden.PBGift\";\n\x10SCNotifyGiftData\x12\'\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x19.dobala.garden.PBGiftData\"4\n\x0cSCNotifyGift\x12$\n\x05gifts\x18\x01 \x03(\x0b\x32\x15.dobala.garden.PBGift\"\x17\n\tCSGiftBuy\x12\n\n\x02id\x18\x01 \x01(\x05\"C\n\tSCGiftBuy\x12\n\n\x02id\x18\x01 \x01(\x05\x12*\n\x07rewards\x18\x02 \x03(\x0b\x32\x19.dobala.garden.PBShowProp\"\x19\n\nCSGiftRead\x12\x0b\n\x03ids\x18\x01 \x03(\x05\"\x19\n\nSCGiftRead\x12\x0b\n\x03ids\x18\x01 \x03(\x05\"X\n\x19\x43SGiftUpdateClientTrigger\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0f\n\x07\x66unc_id\x18\x02 \x01(\x03\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\r\n\x05param\x18\x04 \x01(\x05\"X\n\x19SCGiftUpdateClientTrigger\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0f\n\x07\x66unc_id\x18\x02 \x01(\x03\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\r\n\x05param\x18\x04 \x01(\x05*m\n\tGiftError\x12\x14\n\x10\x65rrGiftErrorNone\x10\x00\x12\x16\n\x10\x65rrGiftErrorInit\x10\xe1\x83\x1e\x12\x1b\n\x15\x65rrGiftErrorOutOfData\x10\xe2\x83\x1e\x12\x15\n\x0f\x65rrGiftErrorBuy\x10\xe3\x83\x1e*_\n\nGiftStatus\x12\x13\n\x0fGiftStatus_Init\x10\x00\x12\x13\n\x0fGiftStatus_Open\x10\x01\x12\x13\n\x0fGiftStatus_Read\x10\x02\x12\x12\n\x0eGiftStatus_Buy\x10\x03\x42H\xaa\x02\x10SteamClient.Game\xca\x02\x17Protobuf\\Garden\\Message\xe2\x02\x18Protobuf\\Garden\\Metadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gift_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020SteamClient.Game\312\002\027Protobuf\\Garden\\Message\342\002\030Protobuf\\Garden\\Metadata'
  _globals['_GIFTERROR']._serialized_start=701
  _globals['_GIFTERROR']._serialized_end=810
  _globals['_GIFTSTATUS']._serialized_start=812
  _globals['_GIFTSTATUS']._serialized_end=907
  _globals['_PBGIFTDATA']._serialized_start=56
  _globals['_PBGIFTDATA']._serialized_end=68
  _globals['_PBGIFT']._serialized_start=70
  _globals['_PBGIFT']._serialized_end=153
  _globals['_SCNOTIFYGIFTFULLINFO']._serialized_start=155
  _globals['_SCNOTIFYGIFTFULLINFO']._serialized_end=256
  _globals['_SCNOTIFYGIFTDATA']._serialized_start=258
  _globals['_SCNOTIFYGIFTDATA']._serialized_end=317
  _globals['_SCNOTIFYGIFT']._serialized_start=319
  _globals['_SCNOTIFYGIFT']._serialized_end=371
  _globals['_CSGIFTBUY']._serialized_start=373
  _globals['_CSGIFTBUY']._serialized_end=396
  _globals['_SCGIFTBUY']._serialized_start=398
  _globals['_SCGIFTBUY']._serialized_end=465
  _globals['_CSGIFTREAD']._serialized_start=467
  _globals['_CSGIFTREAD']._serialized_end=492
  _globals['_SCGIFTREAD']._serialized_start=494
  _globals['_SCGIFTREAD']._serialized_end=519
  _globals['_CSGIFTUPDATECLIENTTRIGGER']._serialized_start=521
  _globals['_CSGIFTUPDATECLIENTTRIGGER']._serialized_end=609
  _globals['_SCGIFTUPDATECLIENTTRIGGER']._serialized_start=611
  _globals['_SCGIFTUPDATECLIENTTRIGGER']._serialized_end=699
# @@protoc_insertion_point(module_scope)
