# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_struct.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13player_struct.proto\x12\rdobala.garden\"\xea\x01\n\rPBBriefPlayer\x12\x0b\n\x03uin\x18\x01 \x01(\x05\x12\x11\n\tserver_id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x04 \x01(\t\x12\x12\n\nrole_level\x18\x05 \x01(\x05\x12\x11\n\tavatar_id\x18\x07 \x01(\x05\x12\x14\n\x0c\x61vatar_frame\x18\x08 \x01(\x05\x12\x10\n\x08title_id\x18\n \x01(\x05\x12\x11\n\tis_online\x18\x0c \x01(\x08\x12\x18\n\x10last_online_time\x18\r \x01(\x03\x12\x0b\n\x03vip\x18\x0e \x01(\x08\x12\x11\n\tip_region\x18\x0f \x01(\tB\x13\xaa\x02\x10SteamClient.Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'player_struct_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020SteamClient.Game'
  _globals['_PBBRIEFPLAYER']._serialized_start=39
  _globals['_PBBRIEFPLAYER']._serialized_end=273
# @@protoc_insertion_point(module_scope)
