# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: talk_struct.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11talk_struct.proto\x12\rdobala.garden*l\n\x0bTalkChannel\x12\x16\n\x12TalkChannel_System\x10\x00\x12\x15\n\x11TalkChannel_World\x10\x01\x12\x17\n\x13TalkChannel_Private\x10\x02\x12\x15\n\x11TalkChannel_Guild\x10\x04*\x1d\n\x08TalkType\x12\x11\n\rTalkType_Text\x10\x00\x42\x13\xaa\x02\x10SteamClient.Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'talk_struct_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020SteamClient.Game'
  _globals['_TALKCHANNEL']._serialized_start=36
  _globals['_TALKCHANNEL']._serialized_end=144
  _globals['_TALKTYPE']._serialized_start=146
  _globals['_TALKTYPE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
