# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_struct.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11task_struct.proto\x12\rdobala.garden\")\n\tPBSubTask\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"q\n\x0bPBTaskGroup\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08progress\x18\x02 \x01(\x03\x12+\n\tsub_tasks\x18\x03 \x03(\x0b\x32\x18.dobala.garden.PBSubTask\x12\x17\n\x0fsub_task_bitmap\x18\x04 \x01(\x0c\"5\n\x06PBTask\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08progress\x18\x02 \x01(\x03\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x42H\xaa\x02\x10SteamClient.Game\xca\x02\x17Protobuf\\Garden\\Message\xe2\x02\x18Protobuf\\Garden\\Metadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_struct_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020SteamClient.Game\312\002\027Protobuf\\Garden\\Message\342\002\030Protobuf\\Garden\\Metadata'
  _globals['_PBSUBTASK']._serialized_start=36
  _globals['_PBSUBTASK']._serialized_end=77
  _globals['_PBTASKGROUP']._serialized_start=79
  _globals['_PBTASKGROUP']._serialized_end=192
  _globals['_PBTASK']._serialized_start=194
  _globals['_PBTASK']._serialized_end=247
# @@protoc_insertion_point(module_scope)
