# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dish_table_message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import prop_struct_pb2 as prop__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64ish_table_message.proto\x12\rdobala.garden\x1a\x11prop_struct.proto\"b\n\x0bPBDishTable\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x12\x0f\n\x07\x64ish_id\x18\x02 \x01(\x05\x12\x10\n\x08\x64ish_num\x18\x03 \x01(\x05\x12\x11\n\tsell_time\x18\x04 \x01(\x03\x12\x10\n\x08\x61\x64\x64ition\x18\x05 \x01(\x05\"L\n\x19SCNotifyDishTableFullInfo\x12/\n\x0b\x64ish_tables\x18\x01 \x03(\x0b\x32\x1a.dobala.garden.PBDishTable\"D\n\x11SCNotifyDishTable\x12/\n\x0b\x64ish_tables\x18\x01 \x03(\x0b\x32\x1a.dobala.garden.PBDishTable\" \n\x11\x43SDishTableUnlock\x12\x0b\n\x03pos\x18\x01 \x01(\x05\" \n\x11SCDishTableUnlock\x12\x0b\n\x03pos\x18\x01 \x01(\x05\"*\n\nCSMakeDish\x12\x0f\n\x07\x64ish_id\x18\x01 \x01(\x05\x12\x0b\n\x03num\x18\x02 \x01(\x05\"L\n\nSCMakeDish\x12\x0f\n\x07\x64ish_id\x18\x01 \x01(\x05\x12-\n\nshow_props\x18\x02 \x03(\x0b\x32\x19.dobala.garden.PBShowProp\"=\n\x10\x43SDishTablePlate\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x12\x0f\n\x07\x64ish_id\x18\x02 \x01(\x05\x12\x0b\n\x03num\x18\x03 \x01(\x05\"=\n\x10SCDishTablePlate\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x12\x0f\n\x07\x64ish_id\x18\x02 \x01(\x05\x12\x0b\n\x03num\x18\x03 \x01(\x05\"\x1f\n\x10\x43SDishTableClear\x12\x0b\n\x03pos\x18\x01 \x01(\x05\"N\n\x10SCDishTableClear\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x12-\n\nshow_props\x18\x02 \x03(\x0b\x32\x19.dobala.garden.PBShowProp\"\"\n\x13\x43SGetDishTableAward\x12\x0b\n\x03pos\x18\x01 \x01(\x05\"Q\n\x13SCGetDishTableAward\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x12-\n\nshow_props\x18\x02 \x03(\x0b\x32\x19.dobala.garden.PBShowPropB\x13\xaa\x02\x10SteamClient.Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dish_table_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020SteamClient.Game'
  _globals['_PBDISHTABLE']._serialized_start=62
  _globals['_PBDISHTABLE']._serialized_end=160
  _globals['_SCNOTIFYDISHTABLEFULLINFO']._serialized_start=162
  _globals['_SCNOTIFYDISHTABLEFULLINFO']._serialized_end=238
  _globals['_SCNOTIFYDISHTABLE']._serialized_start=240
  _globals['_SCNOTIFYDISHTABLE']._serialized_end=308
  _globals['_CSDISHTABLEUNLOCK']._serialized_start=310
  _globals['_CSDISHTABLEUNLOCK']._serialized_end=342
  _globals['_SCDISHTABLEUNLOCK']._serialized_start=344
  _globals['_SCDISHTABLEUNLOCK']._serialized_end=376
  _globals['_CSMAKEDISH']._serialized_start=378
  _globals['_CSMAKEDISH']._serialized_end=420
  _globals['_SCMAKEDISH']._serialized_start=422
  _globals['_SCMAKEDISH']._serialized_end=498
  _globals['_CSDISHTABLEPLATE']._serialized_start=500
  _globals['_CSDISHTABLEPLATE']._serialized_end=561
  _globals['_SCDISHTABLEPLATE']._serialized_start=563
  _globals['_SCDISHTABLEPLATE']._serialized_end=624
  _globals['_CSDISHTABLECLEAR']._serialized_start=626
  _globals['_CSDISHTABLECLEAR']._serialized_end=657
  _globals['_SCDISHTABLECLEAR']._serialized_start=659
  _globals['_SCDISHTABLECLEAR']._serialized_end=737
  _globals['_CSGETDISHTABLEAWARD']._serialized_start=739
  _globals['_CSGETDISHTABLEAWARD']._serialized_end=773
  _globals['_SCGETDISHTABLEAWARD']._serialized_start=775
  _globals['_SCGETDISHTABLEAWARD']._serialized_end=856
# @@protoc_insertion_point(module_scope)
