# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mail_message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import prop_struct_pb2 as prop__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12mail_message.proto\x12\rdobala.garden\x1a\x11prop_struct.proto\"\xe0\x01\n\x06PBMail\x12\x0f\n\x07mail_id\x18\x01 \x01(\x05\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12)\n\nattachment\x18\x05 \x03(\x0b\x32\x15.dobala.garden.PBProp\x12\x13\n\x0b\x63reate_time\x18\x06 \x01(\x03\x12\x0f\n\x07is_read\x18\x07 \x01(\x08\x12\x13\n\x0bis_received\x18\x08 \x01(\x08\x12\x17\n\x0fis_soft_deleted\x18\t \x01(\x08\x12\x16\n\x0e\x66orbid_one_key\x18\n \x01(\x08\"<\n\x14SCNotifyMailFullInfo\x12$\n\x05mails\x18\x03 \x03(\x0b\x32\x15.dobala.garden.PBMail\":\n\x12SCNotifyUpdateMail\x12$\n\x05mails\x18\x03 \x03(\x0b\x32\x15.dobala.garden.PBMail\"\x1d\n\nCSReadMail\x12\x0f\n\x07mail_id\x18\x01 \x03(\x05\"\x1d\n\nSCReadMail\x12\x0f\n\x07mail_id\x18\x01 \x03(\x05\"\x1f\n\x0c\x43SDeleteMail\x12\x0f\n\x07mail_id\x18\x01 \x03(\x05\"\x1f\n\x0cSCDeleteMail\x12\x0f\n\x07mail_id\x18\x01 \x03(\x05\" \n\rCSReceiveMail\x12\x0f\n\x07mail_id\x18\x01 \x03(\x05\"J\n\rSCReceiveMail\x12\x0f\n\x07mail_id\x18\x01 \x03(\x05\x12(\n\x05props\x18\x02 \x03(\x0b\x32\x19.dobala.garden.PBShowPropB\x13\xaa\x02\x10SteamClient.Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mail_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020SteamClient.Game'
  _globals['_PBMAIL']._serialized_start=57
  _globals['_PBMAIL']._serialized_end=281
  _globals['_SCNOTIFYMAILFULLINFO']._serialized_start=283
  _globals['_SCNOTIFYMAILFULLINFO']._serialized_end=343
  _globals['_SCNOTIFYUPDATEMAIL']._serialized_start=345
  _globals['_SCNOTIFYUPDATEMAIL']._serialized_end=403
  _globals['_CSREADMAIL']._serialized_start=405
  _globals['_CSREADMAIL']._serialized_end=434
  _globals['_SCREADMAIL']._serialized_start=436
  _globals['_SCREADMAIL']._serialized_end=465
  _globals['_CSDELETEMAIL']._serialized_start=467
  _globals['_CSDELETEMAIL']._serialized_end=498
  _globals['_SCDELETEMAIL']._serialized_start=500
  _globals['_SCDELETEMAIL']._serialized_end=531
  _globals['_CSRECEIVEMAIL']._serialized_start=533
  _globals['_CSRECEIVEMAIL']._serialized_end=565
  _globals['_SCRECEIVEMAIL']._serialized_start=567
  _globals['_SCRECEIVEMAIL']._serialized_end=641
# @@protoc_insertion_point(module_scope)
