# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prop_struct.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11prop_struct.proto\x12\rdobala.garden\"+\n\x06PBProp\x12\x0f\n\x07prop_id\x18\x01 \x01(\x05\x12\x10\n\x08prop_num\x18\x02 \x01(\x03\"t\n\nPBShowProp\x12\x0f\n\x07prop_id\x18\x01 \x01(\x05\x12\x10\n\x08prop_num\x18\x02 \x01(\x03\x12\x10\n\x08prop_tag\x18\x03 \x01(\t\x12\x0e\n\x06raw_id\x18\x06 \x01(\x05\x12\x0f\n\x07raw_num\x18\x07 \x01(\x03\x12\x10\n\x08\x65xtra_id\x18\n \x01(\x03\"\xa2\x01\n\nPBPropData\x12\x15\n\rbucket_bitmap\x18\x01 \x01(\x0c\x12\x1a\n\x12\x64\x61ily_bucket_count\x18\x02 \x01(\x05\x12\x19\n\x11last_refresh_time\x18\x03 \x01(\x03\x12\x1a\n\x12time_energy_bitmap\x18\x04 \x01(\x0c\x12*\n\x0b\x64\x61ily_props\x18\x06 \x03(\x0b\x32\x15.dobala.garden.PBProp*\x87\x01\n\x07PropTag\x12\x10\n\x0cPropTag_None\x10\x00\x12\x12\n\x0ePropTag_Client\x10\x01\x12\x13\n\x0fPropTag_HomeDog\x10\x02\x12\x18\n\x14PropTag_HomeBuilding\x10\x03\x12\x10\n\x0cPropTag_Card\x10\x05\x12\x15\n\x11PropTag_Transform\x10\x06\x42\x13\xaa\x02\x10SteamClient.Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prop_struct_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020SteamClient.Game'
  _globals['_PROPTAG']._serialized_start=365
  _globals['_PROPTAG']._serialized_end=500
  _globals['_PBPROP']._serialized_start=36
  _globals['_PBPROP']._serialized_end=79
  _globals['_PBSHOWPROP']._serialized_start=81
  _globals['_PBSHOWPROP']._serialized_end=197
  _globals['_PBPROPDATA']._serialized_start=200
  _globals['_PBPROPDATA']._serialized_end=362
# @@protoc_insertion_point(module_scope)
