# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rank_struct.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import player_struct_pb2 as player__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rank_struct.proto\x12\rdobala.garden\x1a\x13player_struct.proto\"^\n\x0cPBRankPlayer\x12,\n\x06player\x18\x01 \x01(\x0b\x32\x1c.dobala.garden.PBBriefPlayer\x12\x12\n\nrank_score\x18\x02 \x01(\x03\x12\x0c\n\x04rank\x18\x03 \x01(\x05\x42\x13\xaa\x02\x10SteamClient.Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rank_struct_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020SteamClient.Game'
  _globals['_PBRANKPLAYER']._serialized_start=57
  _globals['_PBRANKPLAYER']._serialized_end=151
# @@protoc_insertion_point(module_scope)
