# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sign_message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import prop_struct_pb2 as prop__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12sign_message.proto\x12\rdobala.garden\x1a\x11prop_struct.proto\"`\n\nPBSignData\x12\x0f\n\x07sign_id\x18\x01 \x01(\x05\x12\x12\n\nsign_times\x18\x02 \x01(\x05\x12\x15\n\rre_sign_times\x18\x03 \x01(\x05\x12\x16\n\x0elast_sign_time\x18\x04 \x01(\x03\"?\n\x14SCNotifySignFullInfo\x12\'\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x19.dobala.garden.PBSignData\";\n\x10SCNotifySignData\x12\'\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x19.dobala.garden.PBSignData\"\x19\n\x06\x43SSign\x12\x0f\n\x07sign_id\x18\x01 \x01(\x05\"E\n\x06SCSign\x12\x0f\n\x07sign_id\x18\x01 \x01(\x05\x12*\n\x07rewards\x18\x02 \x03(\x0b\x32\x19.dobala.garden.PBShowProp\"\x1b\n\x08\x43SReSign\x12\x0f\n\x07sign_id\x18\x01 \x01(\x05\"G\n\x08SCReSign\x12\x0f\n\x07sign_id\x18\x01 \x01(\x05\x12*\n\x07rewards\x18\x02 \x03(\x0b\x32\x19.dobala.garden.PBShowPropB\x13\xaa\x02\x10SteamClient.Gameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sign_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\020SteamClient.Game'
  _globals['_PBSIGNDATA']._serialized_start=56
  _globals['_PBSIGNDATA']._serialized_end=152
  _globals['_SCNOTIFYSIGNFULLINFO']._serialized_start=154
  _globals['_SCNOTIFYSIGNFULLINFO']._serialized_end=217
  _globals['_SCNOTIFYSIGNDATA']._serialized_start=219
  _globals['_SCNOTIFYSIGNDATA']._serialized_end=278
  _globals['_CSSIGN']._serialized_start=280
  _globals['_CSSIGN']._serialized_end=305
  _globals['_SCSIGN']._serialized_start=307
  _globals['_SCSIGN']._serialized_end=376
  _globals['_CSRESIGN']._serialized_start=378
  _globals['_CSRESIGN']._serialized_end=405
  _globals['_SCRESIGN']._serialized_start=407
  _globals['_SCRESIGN']._serialized_end=478
# @@protoc_insertion_point(module_scope)
